// Countries / territories where our game providers (PG SOFT and partners)
// prohibit operation. Users detected in these locations are blocked from the app.
export const BLOCKED_COUNTRIES = {
  US: 'United States',
  PR: 'Puerto Rico',
  GU: 'Guam',
  VI: 'U.S. Virgin Islands',
  AS: 'American Samoa',
  MP: 'Northern Mariana Islands',
  GB: 'United Kingdom',
  FR: 'France',
  GF: 'French Guiana',
  GP: 'Guadeloupe',
  MQ: 'Martinique',
  RE: 'Réunion',
  YT: 'Mayotte',
  NC: 'New Caledonia',
  PF: 'French Polynesia',
  NL: 'Netherlands',
  CW: 'Curaçao',
  AW: 'Aruba',
  SX: 'Sint Maarten',
  AU: 'Australia',
  IL: 'Israel',
  SG: 'Singapore',
  HK: 'Hong Kong',
  TW: 'Taiwan',
  CN: 'China',
  MO: 'Macau',
  IT: 'Italy',
  ES: 'Spain',
  BE: 'Belgium',
  DK: 'Denmark',
  CZ: 'Czech Republic',
  PT: 'Portugal',
  CH: 'Switzerland',
  RO: 'Romania',
  SE: 'Sweden',
  LT: 'Lithuania',
  LV: 'Latvia',
  EE: 'Estonia',
  UA: 'Ukraine',
  RU: 'Russia',
  TR: 'Turkey',
  IR: 'Iran',
  IQ: 'Iraq',
  SY: 'Syria',
  KP: 'North Korea',
  CU: 'Cuba',
  SD: 'Sudan',
  MM: 'Myanmar',
  AF: 'Afghanistan',
};

export function isBlockedCountry(code) {
  return !!code && Object.prototype.hasOwnProperty.call(BLOCKED_COUNTRIES, String(code).toUpperCase());
}